version: "3.9"
name: wallet-local

networks:
  wallet_network:
    driver: bridge

services:
  postgres:
    restart: always
    image: postgres:15.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=wallet
    volumes:
      - postgres:/data/postgres
    ports:
      - "15435:5432"
    networks:
      - wallet_network

volumes:
  postgres: