version: "3.9"

services:
  backend:
    image: ghcr.io/valykhin/wallet:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_APPLICATION_JSON: '{"logging":{"level":{"ru":{"ivalykhin":{"wallet":"INFO"}}}}}'
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:-50}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:-5000}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      SPRING_KAFKA_SEND_TIMEOUT_MS: ${SPRING_KAFKA_SEND_TIMEOUT_MS:-1000}
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${SPRING_KAFKA_CONSUMER_GROUP_ID:-wallet-service-group}
      SPRING_KAFKA_WALLET_OPERATIONS_TOPIC: ${SPRING_KAFKA_WALLET_OPERATIONS_TOPIC:-wallet-operations}
      WALLET_RETRY_OPTIMISTIC_LOCK_MAX_ATTEMPTS: ${WALLET_RETRY_OPTIMISTIC_LOCK_MAX_ATTEMPTS:-5}
      WALLET_RETRY_OPTIMISTIC_LOCK_DELAY: ${WALLET_RETRY_OPTIMISTIC_LOCK_DELAY:-100}
      WALLET_RETRY_OPTIMISTIC_LOCK_MULTIPLIER: ${WALLET_RETRY_OPTIMISTIC_LOCK_MULTIPLIER:-1.5}
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: ${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED:-true}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:-health,info,prometheus}
      JAVA_OPTS: "-Xms512m -Xmx1024m"
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '4.0'
          memory: 2Gb
        reservations:
          cpus: '2.0'
          memory: 2Gb
    depends_on:
      - postgres
      -  init-kafka-container

  init-kafka-container:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics --bootstrap-server kafka:9092 --list
      kafka-topics --create --partitions 2 --bootstrap-server kafka:9092 --topic wallet-operations
      "

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 64Mb
        reservations:
          cpus: '0.2'
          memory: 32Mb

  postgres:
    restart: always
    image: postgres:15.0
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=wallet
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres: