version: "3.9"

services:
  backend:
    image: ghcr.io/valykhin/wallet:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_APPLICATION_JSON: '{"logging":{"level":{"ru":{"ivalykhin":{"wallet":"INFO"}}}}}'
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:15.0
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=wallet
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres: