version: "3.9"

services:
  backend:
    image: ghcr.io/valykhin/wallet:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_APPLICATION_JSON: '{"logging":{"level":{"ru":{"ivalykhin":{"wallet":"INFO"}}}}}'
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:-50}
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:-5000}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:-kafka:9093}
      SPRING_KAFKA_SEND_TIMEOUT_MS: ${SPRING_KAFKA_SEND_TIMEOUT_MS:-1000}
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${SPRING_KAFKA_CONSUMER_GROUP_ID:-wallet-service-group}
      SPRING_KAFKA_WALLET_OPERATIONS_TOPIC: ${SPRING_KAFKA_WALLET_OPERATIONS_TOPIC:-wallet-operations}
      WALLET_RETRY_OPTIMISTIC_LOCK_MAX_ATTEMPTS: ${WALLET_RETRY_OPTIMISTIC_LOCK_MAX_ATTEMPTS:-5}
      WALLET_RETRY_OPTIMISTIC_LOCK_DELAY: ${WALLET_RETRY_OPTIMISTIC_LOCK_DELAY:-100}
      WALLET_RETRY_OPTIMISTIC_LOCK_MULTIPLIER: ${WALLET_RETRY_OPTIMISTIC_LOCK_MULTIPLIER:-1.5}
      WALLET_RETRY_OPERATION_REQUEST_TIMEOUT: ${WALLET_RETRY_OPERATION_REQUEST_TIMEOUT:-60}
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 768M
        reservations:
          cpus: '0.5'
          memory: 768M
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:15.0
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=wallet
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres: