spring:
  application:
    name: wallet
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl.auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 5000
      auto-commit: false
      pool-name: HikariWalletPool
      validation-timeout: 3000
  kafka:
    enabled: true
    properties:
      security.protocol: PLAINTEXT
    bootstrap-servers: localhost:29093
    send-timeout-ms: 1000
    consumer:
      group-id: wallet-service-group
    client-id: ${HOSTNAME:wallet-default}
    wallet-operations-topic: wallet-operations
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true

wallet:
  retry:
    optimistic-lock:
      max-attempts: 5
      delay: 100
      multiplier: 1.5

management:
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      jvm: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

server:
  tomcat:
    max-keep-alive-requests: 200
    connection-timeout: 3000
    max-threads: 400
  port: 80
  address: 0.0.0.0

info:
  application:
    name: ${spring.application.name}
    description: Wallet application
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'